[workspace]

members = [
  "mogwai",
  "crates/mogwai-html-macro",
  "crates/mogwai-hydrator",
  "examples/sandbox",
  "examples/todomvc",
  #"cookbook"
]


[profile.release]
lto = true
opt-level = 'z'
