[package]
name = "cookbook"
version = "0.1.0"
authors = ["Schell <efsubenovex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
doc-comment = "^0.3"
mogwai = { path = "../mogwai", version = "^0.3" }

[dev-dependencies.web-sys]
version = "^0.3"
features = [
]
